
package service.imp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TestService {


    /**
     * 
     */
    @WebMethod(operationName = "SayHiDefault")
    @Action(input = "http://service/TestService/SayHiDefaultRequest", output = "http://service/TestService/SayHiDefaultResponse")
    public void sayHiDefault();

    /**
     * 
     * @param name
     */
    @WebMethod(operationName = "SayHi")
    @Action(input = "http://service/TestService/SayHiRequest", output = "http://service/TestService/SayHiResponse")
    public void sayHi(
        @WebParam(name = "name", partName = "name")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/TestService/sayHelloRequest", output = "http://service/TestService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
