
package service.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestServiceImpService", targetNamespace = "http://imp.service/", wsdlLocation = "http://192.168.1.55:8080/jaxwsTest/service/test?wsdl")
public class TestServiceImpService
    extends Service
{

    private final static URL TESTSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICEIMPSERVICE_EXCEPTION;
    private final static QName TESTSERVICEIMPSERVICE_QNAME = new QName("http://imp.service/", "TestServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.55:8080/jaxwsTest/service/test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICEIMPSERVICE_WSDL_LOCATION = url;
        TESTSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public TestServiceImpService() {
        super(__getWsdlLocation(), TESTSERVICEIMPSERVICE_QNAME);
    }

    public TestServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICEIMPSERVICE_QNAME, features);
    }

    public TestServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICEIMPSERVICE_QNAME);
    }

    public TestServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICEIMPSERVICE_QNAME, features);
    }

    public TestServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServiceImpPort")
    public TestService getTestServiceImpPort() {
        return super.getPort(new QName("http://imp.service/", "TestServiceImpPort"), TestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServiceImpPort")
    public TestService getTestServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imp.service/", "TestServiceImpPort"), TestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw TESTSERVICEIMPSERVICE_EXCEPTION;
        }
        return TESTSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
